name: Manual Build

on:
  workflow_dispatch: # This adds the "Run workflow" button

jobs:
  run-the-build:
    name: "Trigger Windows Build"
    uses: ./.github/workflows/windows-build-clang.yaml
    with:
      cmakePreset: "Release-windows-clang-static"
      cachePrefix: "static"
      uploadArtifacts: true
    secrets: inherit
